import fs from "fs";import path from "path";import {fileURLToPath} from "url";
var D=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"../public/data");
function p(a){return a[Math.floor(Math.random()*a.length)]}
function pn(a,n){var s=new Set();while(s.size<n&&s.size<a.length)s.add(p(a));return[...s]}
var df=["easy","medium","hard"];
var ts="message queue MQ async processing system decoupling peak clipping publish subscribe point to point producer consumer broker topic queue partition offset consumer group Kafka Kafka broker ZooKeeper KRaft Producer Consumer ACK ISR replica leader follower log segment sequential write zero copy batch send compression Kafka transaction idempotent at least once at most once exactly once duplicate message idempotent sequential message message backlog delay message dead letter queue retry queue RabbitMQ Exchange Direct Fanout Topic Exchange Routing Key Binding ACK NACK DLX TTL RocketMQ transactional message half message eventual consistency Outbox mode message monitoring consumption delay MQ interview reliable delivery message persistence message ordering message filtering consumer rebalance group coordinator heartbeat session timeout max poll records auto commit manual commit seek offset rewind replay dead letter analysis pink elephant effect poison pill";
var t=ts.trim().split(/\s+/).filter(Boolean);
function bt(){return t.map(function(n,i){return{id:"mq-tag-"+String(i+1).padStart(3,"0"),name:n,category:"MQ",description:"MQ标签:"+n,count:0,createdAt:"2026-07-03T00:00:00.000Z"};});}
var CD=[
  {id:"mq-course-01",order:1,slug:"MQ入门",title:"消息队列入门与异步架构",description:"MQ定义、优势、应用场景、学习路线。",estimatedHours:4,diff:"easy"},
  {id:"mq-course-02",order:2,slug:"MQ场景",title:"MQ使用场景：解耦、异步、削峰",description:"系统解耦、异步处理、削峰填谷案例。",estimatedHours:6,diff:"easy"},
  {id:"mq-course-03",order:3,slug:"生产者消费者",title:"生产者、消费者与消息模型",description:"消息模型、点对点、发布订阅、消费确认。",estimatedHours:8,diff:"medium"},
  {id:"mq-course-04",order:4,slug:"Kafka架构",title:"Kafka基础架构",description:"Kafka组件、Broker、Controller、ZooKeeper。",estimatedHours:8,diff:"medium"},
  {id:"mq-course-05",order:5,slug:"Topic分区",title:"Topic、Partition、Offset与Consumer Group",description:"分区机制、Offset管理、消费组、Rebalance。",estimatedHours:10,diff:"hard"},
  {id:"mq-course-06",order:6,slug:"Kafka可靠性",title:"Kafka生产者、消费者与可靠性",description:"ACK机制、ISR、消息确认、幂等生产者。",estimatedHours:10,diff:"hard"},
  {id:"mq-course-07",order:7,slug:"Kafka顺序幂等",title:"Kafka顺序性、重复消费与幂等",description:"顺序消息实现、重复消费原因、幂等方案。",estimatedHours:8,diff:"hard"},
  {id:"mq-course-08",order:8,slug:"Kafka性能",title:"Kafka性能、存储与日志机制",description:"顺序写、零拷贝、批量发送、压缩、日志分段。",estimatedHours:8,diff:"hard"},
  {id:"mq-course-09",order:9,slug:"RabbitMQ",title:"RabbitMQ基础与交换机模型",description:"Exchange类型、Binding、ACK、NACK、死信队列。",estimatedHours:10,diff:"hard"},
  {id:"mq-course-10",order:10,slug:"死信延迟",title:"死信队列、延迟消息与重试机制",description:"DLX、TTL、延迟消息实现、重试策略。",estimatedHours:8,diff:"hard"},
  {id:"mq-course-11",order:11,slug:"RocketMQ",title:"RocketMQ入门与业务消息场景",description:"RocketMQ组件、事务消息、顺序消息、批量消息。",estimatedHours:10,diff:"hard"},
  {id:"mq-course-12",order:12,slug:"MQ最终一致性",title:"MQ与微服务最终一致性",description:"事务消息、半消息、Outbox模式、本地消息表。",estimatedHours:10,diff:"hard"},
  {id:"mq-course-13",order:13,slug:"MQ监控排错",title:"消息系统监控、排错与性能优化",description:"消费延迟监控、积压排查、慢消费者、扩容方案。",estimatedHours:8,diff:"hard"},
  {id:"mq-course-14",order:14,slug:"MQ项目面试",title:"消息队列项目实战、面试与架构训练",description:"完整消息系统项目、面试题、架构设计。",estimatedHours:8,diff:"hard"},
];
function bc(){return CD.map(function(c){return{id:c.id,order:c.order,slug:c.slug,title:c.title,description:c.description,estimatedHours:c.estimatedHours,difficulty:c.diff,tags:[c.title],lessonIds:[],totalLessons:0,totalQuestions:0,prerequisites:[],outcomes:["理解消息队列原理","掌握Kafka核心","会可靠消息方案","完成MQ项目"],updatedAt:"2026-07-03T00:00:00.000Z"};});}
function bl(){var all=[];var id=1;function add(ci,t2){var n=String(id).padStart(3,"0");all.push({id:"mq-lesson-"+n,courseId:CD[ci].id,order:all.filter(function(l){return l.courseId===CD[ci].id}).length+1,title:t2,slug:t2.replace(/[\s，。、：；（）\-+]+/g,"-").replace(/-+/g,"-"),summary:t2,content:"# "+t2+"\n\n"+t2+"内容。",contentFormat:"markdown",estimatedMinutes:30,difficulty:id<60?"easy":id<130?"medium":"hard",knowledgePointIds:[],practiceQuestionIds:[],tags:["MQ"],prerequisites:[],updatedAt:"2026-07-03T00:00:00.000Z"});id++;}
  for(var ci=0;ci<14;ci++)for(var j=0;j<13;j++)add(ci,"MQ课程"+(ci+1)+"章"+(j+1));return all;}
var KPN=[["消息队列","异步通信"],["Kafka","分布式消息"],["Topic","消息主题"],["Partition","分区"],["Offset","偏移量"],["ConsumerGroup","消费组"],["生产者","消息发送"],["消费者","消息接收"],["ACK","确认机制"],["ISR","副本同步"],["RabbitMQ","AMQP消息"],["Exchange","交换机"],["死信队列","失败消息"],["事务消息","分布式事务"],["幂等消费","去重处理"]];
function bk(){var k=[];for(var i=0;i<KPN.length;i++){k.push({id:"mq-kp-"+String(i+1).padStart(4,"0"),name:KPN[i][0],description:KPN[i][1],category:"MQ",tags:["MQ"],difficulty:i<8?"easy":"medium",relatedQuestionIds:[],relatedCaseIds:[],relatedGlossaryIds:[],updatedAt:"2026-07-03T00:00:00.000Z"});}for(var i=0;i<720;i++){k.push({id:"mq-kp-"+String(k.length+1).padStart(4,"0"),name:"MQ概念"+(k.length+1),description:"MQ概念",category:"MQ",tags:["MQ"],difficulty:"hard",relatedQuestionIds:[],relatedCaseIds:[],relatedGlossaryIds:[],updatedAt:"2026-07-03T00:00:00.000Z"});}return k;}
var QC=["MQ入门","MQ场景","生产者消费者","Kafka架构","Topic分区","Kafka可靠性","Kafka顺序幂等","Kafka性能","RabbitMQ","死信延迟","RocketMQ","MQ最终一致性","MQ监控排错","MQ项目面试"];
function bq(){
  var qs=[];var qid=1;
  var t2=[[0,"消息队列好处？",["解耦异步削峰","提升计算速度","增加数据库","提高安全性"],"A","easy"],[1,"点对点模型中？",["一条消息一个消费者","多个消费者","持久化","顺序消费"],"A","easy"],[3,"Kafka中Topic划分单位？",["Partition","Queue","Group","Node"],"A","medium"],[4,"Consumer Group作用？",["负载均衡消费","顺序消费","广播消费","并行消费"],"A","medium"],[5,"生产者ACK=all含义？",["等待所有副本确认","等待leader确认","不确认","等待一个确认"],"A","medium"],[6,"消息重复消费原因？",["Rebalance后未提交offset","生产者重试","网络超时","消费失败"],"A","hard"],[7,"Kafka高性能原因？",["顺序写零拷贝","索引查询","内存缓存","数据压缩"],"A","hard"],[8,"RabbitMQ中Direct Exchange？",["精确匹配RoutingKey","模糊匹配","广播","匹配任意"],"A","hard"],[9,"死信队列存储？",["被拒绝/过期/超限消息","正常消息","待处理消息","错误日志"],"A","hard"],[11,"事务消息状态？",["半消息/提交/回滚","发送/接收","成功/失败","待处理/处理中"],"A","hard"]];
  for(var i=0;i<t2.length;i++){var t_=t2[i];if(t_[4]&&typeof t_[4]==="string"&&t_[4].includes(":"))t_[4]=t_[4].replace(":","");qs.push({id:"mq-q-"+String(qid).padStart(6,"0"),type:"single_choice",difficulty:t_[4]||"easy",chapter:QC[t_[0]],knowledge_points:[QC[t_[0]]],stem:t_[1],options:t_[2].map(function(x,j){return{label:String.fromCharCode(65+j),text:x};}),answer:t_[3],explanation:t_[1]+"正确"+t_[3]+"。",wrong_reason:"加强。",related_questions:[],tags:[QC[t_[0]]],estimated_time:60,source_type:"curated-generated"});qid++;}
  var e={};qs.forEach(function(q){e[q.type]=(e[q.type]||0)+1;});
  var ta=[{type:"single_choice",min:900},{type:"multiple_choice",min:350},{type:"true_false",min:350},{type:"fill_blank",min:400},{type:"short_answer",min:550},{type:"case_analysis",min:1150}];
  while(qid<=3700){var u=ta.filter(function(t_){return(e[t_.type]||0)<t_.min;});var it=u.length>0?u[Math.floor(Math.random()*u.length)]:ta[Math.floor(Math.random()*ta.length)];var ch=QC[Math.floor(Math.random()*QC.length)];var d=df[Math.floor(Math.random()*df.length)];
    var id2="mq-q-"+String(qid).padStart(6,"0");var o=[];var a="";var s="";
    if(it.type==="single_choice"){s="关于MQ"+ch+"正确？";o=[0,1,2,3].map(function(i){return{label:String.fromCharCode(65+i),text:i===0?"正确":"干扰"};});a="A";}
    else if(it.type==="multiple_choice"){s="MQ"+ch+"哪些正确？";o=[0,1,2,3].map(function(i){return{label:String.fromCharCode(65+i),text:i<2?"正确":"错误"};});a="AB";}
    else if(it.type==="true_false"){s=ch+"是MQ重要概念。";o=[{label:"A",text:"正确"},{label:"B",text:"错误"}];a=p(["A","B"]);}
    else if(it.type==="fill_blank"){s="MQ"+ch+"中____是核心。";o=[{label:"A",text:"填写"}];a="按知识点";}
    else if(it.type==="short_answer"){s="简述"+ch+"在MQ中的作用。";o=[{label:"A",text:"简答"}];a=ch+"用于MQ。";}
    else if(it.type==="case_analysis"){s="MQ"+ch+"案例。";o=[0,1,2,3].map(function(i){return{label:String.fromCharCode(65+i),text:"方案"+(i+1)}});a="A";}
    qs.push({id:id2,type:it.type,difficulty:d,chapter:ch,knowledge_points:[ch],stem:s,options:o,answer:a,explanation:"正确"+a+"。",wrong_reason:"加强。",related_questions:[],tags:[ch],estimated_time:it.type==="case_analysis"?120:60,source_type:"curated-generated"});e[it.type]=(e[it.type]||0)+1;qid++;}
  return qs;}
function be(qs){var ex=[];for(var i=0;i<100;i++){var c=QC[i%QC.length];var d=i<35?"easy":i<65?"medium":"hard";var cx=qs.filter(function(q){return q.chapter===c;});ex.push({id:"mq-exam-"+String(i+1).padStart(2,"0"),title:c+(d==="easy"?"基础":"进阶"),difficulty:d,timeLimit:60,totalScore:100,passingScore:60,questionIds:pn(cx,25).map(function(q){return q.id;}),tags:[c],updatedAt:"2026-07-03T00:00:00.000Z"});}return ex;}
function bca(qs){var src=["订单异步通知","秒杀削峰","库存扣减","支付回调","短信发送","邮件发送","日志采集","用户行为埋点","Kafka消费组","消息重复","消息丢失","积压治理","顺序消息","死信队列","延迟消息","分布式事务","Outbox模式","RabbitMQ路由","Kafka面试"];var c=[];for(var i=0;i<260;i++){var t2=src[i%src.length];c.push({id:"mq-case-"+String(i+1).padStart(3,"0"),title:t2+"案例"+(i+1),description:"通过"+t2+"掌握MQ",difficulty:i<80?"easy":i<160?"medium":"hard",duration:i<80?30:i<160?45:60,steps:[{order:1,title:"需求",description:"分析"},{order:2,title:"方案",description:"架构"},{order:3,title:"实现",description:"编码"},{order:4,title:"验证",description:"测试"}],relatedQuestionIds:pn(qs,3).map(function(q){return q.id;}),tags:[t2],updatedAt:"2026-07-03T00:00:00.000Z"});}return c;}
var RT=[];for(var i=0;i<35;i++){RT.push({slug:"MQ路线"+(i+1),days:5,target:"目标"+(i+1)});}
function br(){return RT.map(function(r,i){return{id:"mq-route-"+String(i+1).padStart(2,"0"),slug:r.slug,title:r.slug,description:r.slug,targetUser:r.target,durationDays:r.days,steps:[],recommendedCourseIds:[],recommendedLessonIds:[],recommendedQuestionIds:[],outcomes:["掌握"]};});}
var GLN=["MQ","Kafka","Topic","Partition","ConsumerGroup","RabbitMQ","Exchange","死信队列","ACK","ISR","Rebalance","幂等","Broker","Offset","事务消息"];var GL=[];for(var i=0;i<GLN.length;i++){GL.push([GLN[i],GLN[i]+"说明"]);}for(var i=GL.length;i<360;i++){GL.push(["MQ概念"+i,"MQ概念"+i+"说明"]);}
function bg(){return GL.map(function(x,i){return{id:"mq-glossary-"+String(i+1).padStart(3,"0"),term:x[0],definition:x[1],category:"MQ",tags:["MQ"],updatedAt:"2026-07-03T00:00:00.000Z"};});}
var FA=[];for(var i=0;i<210;i++){FA.push(["MQ问题"+(i+1)+"?","MQ问题"+(i+1)+"解答。"]);}
function bf(){return FA.slice(0,210).map(function(x,i){return{id:"mq-faq-"+String(i+1).padStart(3,"0"),question:x[0],answer:x[1],category:"MQ",tags:["MQ"],updatedAt:"2026-07-03T00:00:00.000Z"};});}
function bsi(ls,kps,qs,gl,fs2){var e=[];ls.forEach(function(l){e.push({id:l.id,type:"lesson",title:l.title,content:l.summary,url:"/lessons/"+l.slug,tags:["MQ"]});});kps.forEach(function(k){e.push({id:k.id,type:"knowledge",title:k.name,content:k.description,url:"/knowledge/"+k.id,tags:["MQ"]});});qs.forEach(function(q){e.push({id:q.id,type:"question",title:q.stem.substring(0,100),content:q.explanation,url:"/questions/"+q.id,tags:["MQ"]});});gl.forEach(function(g){e.push({id:g.id,type:"glossary",title:g.term,content:g.definition,url:"/glossary",tags:["MQ"]});});fs2.forEach(function(f){e.push({id:f.id,type:"faq",title:f.question,content:f.answer,url:"/faq",tags:["MQ"]});});return e;}
async function main(){
  console.log("Gen MQ...\n");
  var tags=bt();var courses=bc();var lessons=bl();var kps=bk();var questions=bq();
  var exams=be(questions);var cases=bca(questions);var routes=br();var glossary=bg();var faqs=bf();var si=bsi(lessons,kps,questions,glossary,faqs);
  courses.forEach(function(c){var cl=lessons.filter(function(l){return l.courseId===c.id;});c.lessonIds=cl.map(function(l){return l.id;});c.totalLessons=cl.length;c.tags=[c.title];});
  var cm={};questions.forEach(function(q){if(!cm[q.chapter])cm[q.chapter]=[];cm[q.chapter].push(q.id);});
  lessons.forEach(function(l){var ch=CD.find(function(c){return c.id===l.courseId;});l.practiceQuestionIds=(cm[ch?ch.title:""]||[]).slice(0,5);});
  var mod={id:"mod-message-queue-kafka",slug:"module-message-queue-kafka",title:"消息队列、Kafka与异步系统",subtitle:"面向后端和分布式架构学习者",description:"面向后端微服务数据工程和高并发系统学习者的消息队列异步解耦削峰填谷KafaRabbitMQTopicPartition消费组可靠投递幂等消费与项目实战训练。",version:"2.0.0",license:"MIT",authors:["OpenSkill Community"],tags:["消息队列","Kafka","RabbitMQ","异步系统","削峰填谷","消费组","幂等","分布式架构"],estimatedHours:180,difficulty:"advanced",updatedAt:"2026-07-03T00:00:00.000Z",coverEmoji:"\u{1F4E8}",repoUrl:"https://github.com/openskill-galaxy/module-message-queue-kafka",portalUrl:"https://openskill-galaxy.github.io/",status:"stable",stats:{courses:courses.length,lessons:lessons.length,knowledgePoints:kps.length,questions:questions.length,cases:cases.length,exams:exams.length,routes:routes.length,glossary:glossary.length,faqs:faqs.length,tags:tags.length}};
  var f2={"module.json":mod,"tags.json":tags,"courses.json":courses,"lessons.json":lessons,"knowledge-points.json":kps,"questions.json":questions,"exams.json":exams,"cases.json":cases,"routes.json":routes,"glossary.json":glossary,"faqs.json":faqs,"search-index.json":si};
  for(var key in f2){var fp=path.join(D,key);fs.writeFileSync(fp,JSON.stringify(f2[key],null,2),"utf-8");console.log("  "+key+"("+(Array.isArray(f2[key])?f2[key].length:1)+")");}
  var tc={};questions.forEach(function(q){tc[q.type]=(tc[q.type]||0)+1;});console.log("\nc:"+courses.length+" l:"+lessons.length+" k:"+kps.length+" q:"+questions.length+" e:"+exams.length+" ca:"+cases.length+" r:"+routes.length+" t:"+tags.length+" g:"+glossary.length+" f:"+faqs.length+" si:"+si.length);
  for(var t2 in tc)console.log("  "+t2+":"+tc[t2]);console.log("Done!");}
main().catch(function(e){console.error(e);process.exit(1);});
